# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set CamelCase and not included whitespace
# You are supposed to set at least Dynamixel ID
pan:
  ID: 1
  LED: 0
  Operating_Mode: 1
tilt:
  ID: 2
  LED: 0
  Operating_Mode: 1
